stages:
  - validate
  - test
  - build
  - docker-build

validate-job:
  stage: validate
  image: node:20-alpine
  script:
    - node --version
    - npm --version

test-job:
  stage: test
  image: node:20-alpine
  script:
    - cd app
    - npm ci
    - npm test

build-job:
  stage: build
  image: node:20-alpine
  script:
    - cd app
    - npm ci
    - echo "Build completed"

docker-build-job:
  stage: docker-build
  image: docker:20.10.24

  script:
    - docker version
    - docker build -t node-time-app:ci ./app
    - docker images
